name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # 當您推送到 main 分支時觸發
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 部署編譯後的 dist 資料夾
          branch: gh-pages # 部署到 gh-pages 分支
